#!/bin/sh

OID=.1.3.6.1.4.1.2021.10.1
HOST=$1

SNMPWALK=/usr/bin/snmpwalk
SNMPGET=/usr/bin/snmpget
OPTIONS="-t 1 -r 2 -Ov -OQ"

STATE_OK=0
STATE_WARNING=1
STATE_CRITICAL=2
STATE_UNKNOWN=3
STATE_DEPENDENT=4

counter=0
for value in `${SNMPWALK} ${OPTIONS} ${HOST} ${OID}.100 2>/dev/null`; do
    counter=$(( counter+1 ))

    # Pierre test change load average 
    #if [ $value -eq 1 ]; then
    if [ $value -eq 2 ]; then
	echo `${SNMPGET} ${OPTIONS} ${HOST} ${OID}.101.${counter}`
	exit $STATE_CRITICAL
    fi	

done

# No values returned from snmpwalk
[ $counter -eq 0 ] && exit $STATE_UNKNOWN

resultstr=""
for value in `${SNMPWALK} ${OPTIONS} ${HOST} ${OID}.3 2>/dev/null`; do
    resultstr="${resultstr}${value}, "
done
echo "${resultstr:0:${#resultstr}-2}"
exit $STATE_OK
