#!/bin/sh

HOST=$1
VHOST=$2
USER=$3
PASSWORD=$4

URL="/fcgi-bin/tific.fcg?func=server.ping"
TMPDIR=/tmp
WGET=/usr/bin/wget
COOKIEFILE=${TMPDIR}/nagios.${VHOST}.cookies
OPTIONS="--tries 1 -q -O - --timeout=3 --user-agent=check_http(nagios) --no-http-keep-alive --keep-session-cookies --save-cookies=${COOKIEFILE}"

STATE_OK=0
STATE_WARNING=1
STATE_CRITICAL=2
STATE_UNKNOWN=3
STATE_DEPENDENT=4


umask 077
[ -n "$USER" ] && OPTIONS="${OPTIONS} --user=${USER} --password=${PASSWORD}"
[ -f "$COOKIEFILE" ] && OPTIONS="${OPTIONS} --load-cookies=${COOKIEFILE}"

${WGET} ${OPTIONS} "http://${VHOST}${URL}" | grep "pong" &>/dev/null

if [ $? -eq 0 ]; then
    echo $VHOST OK
    exit $STATE_OK
else
    rm -f "${COOKIEFILE}"
    echo $?
    echo $VHOST ERROR
    exit $STATE_CRITICAL
fi


