#!/bin/bash

# check_tific_auth
# Written by Brad Clark
#
# Checks a TiFiC server instance that requires username and password authorization.
#

progname=check_tific
version=2.0
author="Brad Clark"

if [ $# -lt 1 ]; then
	echo "Usage: $0 -i ip -h vhost [-p port] [-U username] [-P password] [-D] [-S]"
	exit
fi

port=80
checkhttp="/usr/local/icinga/libexec/check_http"
useragent="TiFiC Client"
dbcheck=0
statuschk=0
resp="OK"
url="/fcgi-bin/tific.fcg?func=server.status"

while getopts ":i:h:p:U:P:DS" opt; do
	case $opt in
	i) ipaddr=$OPTARG ;;
	h) vhost=$OPTARG ;;
	p) port=$OPTARG ;;
	U) username=$OPTARG ;;
	P) password=$OPTARG ;;
	D) dbcheck=1 ;;
	S) statuschk=1 ;;
	\?)
		echo "Invalid option: -$OPTARG" >&2
		echo "Usage: $0 -i ip -h vhost [-p port] [-D] [-S] [-u username] [-p password]"
		exit
	;;
	:)
		echo "Option -$OPTARG requires an argument" >&2
		exit
	;;
	esac
done

if [ $statuschk -eq 1 ]; then
	if [ $dbcheck -eq 1 ]; then
		url="/fcgi-bin/tific.fcg?func=server.ping&readCacheBlock=1"
	else
		url="/fcgi-bin/tific.fcg?func=server.ping"
	fi
	resp="pong"
fi

if [ ! -n "$username" ]; then
#	echo "No username provided. Assuming no auth required."
	$checkhttp -s $resp -p $port -A "$useragent" -u "$url" -H $vhost -I $ipaddr

elif [ ! -n "$password" ]; then
#	echo "No password provided."
	exit 1
else
	$checkhttp -s $resp -p $port -A "$useragent" -u "$url" -H $vhost -I $ipaddr -a $username:$password
fi
