#!/bin/bash

# nagios return values
export STATE_OK=0
export STATE_WARNING=1
export STATE_CRITICAL=2
export STATE_UNKNOWN=3  
export STATE_DEPENDENT=4

# temperature values for warning or critical / hdd (from datasheet)
MAXTEMPCRIT="95"
MINTEMPCRIT="55"
MAXTEMPWARN="85"
MINTEMPWARN="65"
                                        
# check temperature for warning or critical values
function checkTemperature () {

        true=$(echo "$1 >= $MAXTEMPWARN" | bc)
                if [ $true = 1 ] ; then
                        returnValue=$STATE_WARNING ;
                fi

        true=$(echo "$1 >= $MAXTEMPCRIT" | bc)
                if [ $true = 1 ] ; then
                        returnValue=$STATE_CRITICAL ;
                fi

        true=$(echo "$1 <= $MINTEMPWARN" | bc)
                if [ $true = 1 ] ; then
                        returnValue=$STATE_WARNING ;
                fi

        true=$(echo "$1 <= $MINTEMPCRIT" | bc)
                if [ $true = 1 ] ; then
                        returnValue=$STATE_CRITICAL ;
                fi
        return $returnValue
}


currentTemp=`snmpget -v1 -c XaZG1Xvw 10.202.205.90 uioSensorStatusTemperatureDegF.2.1 | awk '{print $4}'`
checkTemperature $currentTemp
intReturn=$?
outputText="External Temp: $currentTemp°F | 'ExternalTemp °F'=$currentTemp;$MAXTEMPWARN;$MAXTEMPCRIT" ;

echo -e $outputText
exit $intReturn
